<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x86</PlatformTarget>
    <ApplicationIcon>Resources\view_text.ico</ApplicationIcon>
    <AssemblyTitle>Windows Path Editor</AssemblyTitle>
    <Description>Application for easily editing the Windows PATH</Description>
    <Company>Rico Huijbers</Company>
    <Product>Windows Path Editor</Product>
    <Copyright>© 2013 Rico Huijbers</Copyright>
    <Version>1.7.0.0</Version>
    <AssemblyVersion>1.7.0.0</AssemblyVersion>
    <FileVersion>1.7.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Resources\**" />
    <Resource Include="Resources\accept.png" />
    <Resource Include="Resources\add.png" />
    <Resource Include="Resources\cross.png" />
    <Resource Include="Resources\delete.png" />
    <Resource Include="Resources\error.png" />
    <Resource Include="Resources\folder_explore.png" />
    <Resource Include="Resources\view_text.ico" />
  </ItemGroup>
</Project>
